### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by sg-s** [moyaproject/notes#2]
I see that it's meant to be a self-hosted project, so it would make sense to provide at least some minimial install instructions. I'm happy to help write the docs if you need.

**Comment by willmcgugan** [comment]
You're right. Will add installation instructions shortly.

**Comment by willmcgugan** [comment]
I've added install instructions here...

https://github.com/moyaproject/notes/blob/master/INSTALL.md

**Comment by sg-s** [comment]
thanks!
