### ISSUE TITLE
More of a request than an issue - Heroku deploy button

### ISSUE THREAD

**Issue by xxdesmus** [moyaproject/notes#3]
It'd be really cool to get a Heroku 1 click to deploy button for this project -> https://blog.heroku.com/archives/2014/8/7/heroku-button

Looks very cool, looking forward to giving this a try.

**Comment by willmcgugan** [comment]
I'll look in to that!

**Comment by willmcgugan** [comment]
Done! See the readme.

**Comment by xxdesmus** [comment]
Thank you!
